### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by ElectronicsArchiver** [dvdvideo1234/LaserSTool#24]
About your contribution guidelines

> Use two spaces instead of one tab for indentation
All new files must be lower case for linux support
Line endings must always be unix complaint LF
Trim the tailing space before you save

Just use a `.editorconfig`

```editorconfig
root = true

[*]
end_of_line = lf
insert_final_newline = true


[*.{lua,md}]
charset = utf-8
indent_style = space

[*lua]
indent_size = 2

[*.md]
indent_size = 4
```

And since when does Linux require lower case filenames??

**Comment by dvdvideo1234** [comment]
Thanks. Will merge right away ;)

**Comment by dvdvideo1234** [comment]
@ElectronicsArchiver closed in https://github.com/dvdvideo1234/LaserSTool/commit/99839499049fa9e9e8c3610814e3ec536328ba2b
