### ISSUE TITLE
Repository Suggestions

### ISSUE THREAD

**Issue by ElectronicsArchiver** [dvdvideo1234/LaserSTool#25]
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

## ![Badge Suggestions]

  <br>

- **Update Description**

  `Laser STool addon for Garry's Mod.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`
  
  <br>

<br>
<br>

**Comment by dvdvideo1234** [comment]
Hmm.. Is this supposed to be in remade or something ?

**Comment by ElectronicsArchiver** [comment]
> Hmm.. Is this supposed to be in remade or something ?

I'm not sure what you mean with that..

**Comment by ElectronicsArchiver** [comment]
Add? Those are modifications I'm suggesting.

The description can be changed by clicking
the cog icon on the repositories front page.

**Comment by dvdvideo1234** [comment]
Description: `Official repository of the Laser STool for Garry's mod`

![image](https://user-images.githubusercontent.com/9112662/181059587-bf5ef4dd-8ba7-4bdc-8a0a-ba765cd28066.png)
![image](https://user-images.githubusercontent.com/9112662/181059673-4232a234-03ab-48e4-ab4e-9eaa83be9ae5.png)
